# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20170313_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='sol_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
