# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 09:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('riddles', '0003_solution_sol_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='submitted',
        ),
        migrations.AddField(
            model_name='info',
            name='member1',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riddles',
            name='text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='solution',
            name='sol_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
