# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0004_auto_20170314_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='member1',
            field=models.CharField(default='x', max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='riddle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rid', to='riddles.Riddles'),
        ),
    ]
