# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0007_solution_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
