# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0009_solution_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over', models.BooleanField(default=False)),
            ],
        ),
    ]
