# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0010_terminate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
