# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0011_auto_20170315_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
            ],
        ),
    ]
