# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0012_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='member4',
            field=models.CharField(default='-', max_length=20),
        ),
        migrations.AlterField(
            model_name='info',
            name='member1',
            field=models.CharField(default='Leader', max_length=20),
        ),
    ]
